title: Chroniken der Schwertküste
description: Das digitale Archiv unserer D&D-Kampagne in Faerûn.

# Theme einbinden
remote_theme: just-the-docs/just-the-docs

# Suchfunktion aktivieren
search_enabled: true

nav_fold: false
