title: Chroniken der Schwertküste
description: Das digitale Archiv unserer D&D-Kampagne in Faerûn.

# Theme einbinden
remote_theme: just-the-docs/just-the-docs

# Suchfunktion aktivieren
search_enabled: true

# Farbschema festlegen (dark, light oder system)
color_scheme: dark

# Zusatz-Einstellungen
aux_links:
  "GitHub Repository": "https://github.com/Bubbletea95/DnD-Stuff"
